<a href="https://colab.research.google.com/github/Rakib-Ul-Haque/SecureK-Means/blob/main/SecureK_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## **General K-means with Manhattan Distance**

In [322]:
# # Library Declaration  
# import numpy as np
# import pandas as pd 
# # Data Input
# df = pd.read_table('breast-cancer-wisconsin.data', sep=',', names=["Sample code number", "Clump Thickness", "Uniformity of Cell Size", "Uniformity of Cell Shape", "Marginal Adhesion", "Single Epithelial Cell Size","Bare Nuclei", "Bland Chromatin", "Normal Nucleoli","Mitoses","Class"]) 
# # print(df.head)

In [323]:
# # Data Cleaning
# df["Bare Nuclei"][df["Bare Nuclei"]=='?']='0'
# df["Bare Nuclei"] = df["Bare Nuclei"].astype(str).astype(int)
# # df.info()
# # pd.to_numeric(df["Bare Nuclei"])

In [324]:
# # Data Cleaning
# df=df.drop(["Sample code number"], axis = 1)
# # print(df.shape)

In [325]:
# # Data Cleaning
# def Class_value(Class): 
#      if Class == 2: 
#          return 1
#      else: 
#          return 0
  
# df['Class'] = df['Class'].apply(Class_value) 
# #df['Class'].head(10)

In [326]:
# sf=df
# ll = sf["Class"].astype(float).values.tolist()
# ll

In [327]:
# sf=df
# y = sf["Class"].astype(float).values.tolist()
# # y

In [328]:
# df=df.drop(["Class"], axis = 1)

In [329]:
# dataset = df.astype(float).values.tolist()

# X = df.values #returns a numpy array
# X

In [330]:
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt

# from sklearn.cluster import KMeans
# from sklearn.preprocessing import StandardScaler, normalize
# from sklearn.decomposition import PCA
# from sklearn.metrics import silhouette_score

In [331]:
# def distance(self, x1, x2):
    #   distance = 0.0
    #   for i in range(len(x1)-1):
    #     if (x1[i]>=x2[i]):
    #       distance +=(x1[i] - x2[i])
    #     else:
    #       distance += (x2[i] - x1[i])
      # #print(distance)
    #   return distance#np.sqrt(np.sum((x1-x2)**2))
      
    # calculate the Manhatan distance between two vectors
    # def manhatan_distance(row1, row2):
    #   distance = 0.0
    #   for i in range(len(row1)-1):
    #     if (row1[i]>=row2[i]):
    #       distance +=(row1[i] - row2[i])
    #     else:
    #       distance += (row2[i] - row1[i])
    #   return distance

In [332]:
# class KMeans:
    
#     def __init__(self, k=5, n_iter=100, plot_step=False):
        
#         self.k = k
#         self.n_iter = n_iter
#         self.plot_step = plot_step
#         self.clusters = [[] for _ in range(self.k)]    # list of each cluster
#         self.centroids = []     # center of each cluster
        
#     def distance(self, x1, x2):
#       disce = 0.0
#       for i in range(len(x1)-1):
#         if (x1[i]>=x2[i]):
#           disce +=(x1[i] - x2[i])
#         else:
#           disce += (x2[i] - x1[i])
#       return disce
#       #print(distance)


#     # def distance(self, x1, x2):
#     #     return np.sqrt(np.sum((x1-x2)**2))
    
#     def cluster_plot(self):
        
#         fig, ax = plt.subplots(figsize=(12, 8))
        
#         for i, index in enumerate(self.clusters):
#             point = self.X[index].T
#             ax.scatter(*point)
        
#         for centroid in self.centroids:
#             ax.scatter(*centroid, marker='x', color='black', linewidth=2)
#         plt.show()
        
#     def predict(self, X):
        
#         self.X = X
#         self.n_samples, self.n_features = X.shape
        
#         # initialize k random centroids
#         k_random_sample_ids = np.random.choice(self.n_samples, self.k, replace=False)
#         self.centroids = [self.X[ids] for ids in k_random_sample_ids]
        
#         # optimize clusters
#         for _ in range(self.n_iter):
            
#             # update clusters
#             self.clusters = self._create_clusters(self.centroids)     # get clusters from create clusters
#             if self.plot_step:
#                 self.cluster_plot()
                
#             # update centroids
#             old_centroids = self.centroids
#             self.centroids = self._get_new_centroids(self.clusters)
            
#             # check clusters converged
#             if self._is_converged(old_centroids, self.centroids):
#                 break
                
#         return self._get_cluster_label(self.clusters)
    
            
#     def _create_clusters(self, centroids):
        
#         clusters = [[] for _ in range(self.k)]
        
#         for ids, sample in enumerate(self.X):
#             centroid_id = self._closest_centroid(sample, centroids)
#             clusters[centroid_id].append(ids)
#         return clusters
            
            
#     def _closest_centroid(self, sample, centroids):
        
#         distances = [self.distance(sample, centroid) for centroid in centroids]
#         closest_id = np.argmin(distances)
#         return closest_id
        
#     def _get_new_centroids(self, clusters):
        
#         centroids = np.zeros((self.k, self.n_features))
#         for cluster_id, cluster in enumerate(clusters):
#             new_centroid = np.mean(X[cluster], axis=0)
#             centroids[cluster_id] = new_centroid
#         return centroids
    
#     def _is_converged(self, old_centroids, new_centroids):
        
#         distances = [self.distance(old_centroids[i], new_centroids[i]) for i in range(self.k)]
#         return sum(distances) == 0
    
#     def _get_cluster_label(self, clusters):
        
#         labels = np.empty(self.n_samples)
#         for cluster_id, cluster in enumerate(clusters):
#             for sample_id in cluster:
#                 labels[sample_id] = cluster_id
#         return labels

In [333]:
# class KMeans:
#   def __init__(self, k=5, n_iter=100, plot_step=False):
#     self.k = k
#     self.n_iter = n_iter
#     self.plot_step = plot_step
#     self.clusters = [[] for _ in range(self.k)]    # list of each cluster
#     self.centroids = []     # center of each cluster
  
#   def distance(self, x1, x2):
#     return np.sqrt(np.sum((x1-x2)**2))
  
#   def cluster_plot(self):
#     fig, ax = plt.subplots(figsize=(12, 8))
    
#     for i, index in enumerate(self.clusters):
#       point = self.X[index].T
#       ax.scatter(*point)
      
#     for centroid in self.centroids:
#       ax.scatter(*centroid, marker='x', color='black', linewidth=2)
#       plt.show()
  
#   def predict(self, X):
#     self.X = X
#     self.n_samples, self.n_features = X.shape
#     # initialize k random centroids
#     k_random_sample_ids = np.random.choice(self.n_samples, self.k, replace=False)
#     self.centroids = [self.X[ids] for ids in k_random_sample_ids]
#     # optimize clusters
#     for _ in range(self.n_iter):
#       # update clusters
#       self.clusters = self._create_clusters(self.centroids)     # get clusters from create clusters
#       if self.plot_step:
#         self.cluster_plot()
#         # update centroids
#         old_centroids = self.centroids
#         self.centroids = self._get_new_centroids(self.clusters)
#         # check clusters converged
#         if self._is_converged(old_centroids, self.centroids):
#           break
#     return self._get_cluster_label(self.clusters)
    
#   def _create_clusters(self, centroids):
#     clusters = [[] for _ in range(self.k)]
#     for ids, sample in enumerate(self.X):
#       centroid_id = self._closest_centroid(sample, centroids)
#       clusters[centroid_id].append(ids)
#     return clusters
  
#   def _closest_centroid(self, sample, centroids):
#     distances = [self.distance(sample, centroid) for centroid in centroids]
#     closest_id = np.argmin(distances)
#     return closest_id
    
#   def _get_new_centroids(self, clusters):
#     centroids = np.zeros((self.k, self.n_features))
#     for cluster_id, cluster in enumerate(clusters):
#       new_centroid = np.mean(X[cluster], axis=0)
#       centroids[cluster_id] = new_centroid
#     return centroids
    
#   def _is_converged(self, old_centroids, new_centroids):
#     distances = [self.distance(old_centroids[i], new_centroids[i]) for i in range(self.k)]
#     return sum(distances) == 0
    
#   def _get_cluster_label(self, clusters):
#     labels = np.empty(self.n_samples)
#     for cluster_id, cluster in enumerate(clusters):
#       for sample_id in cluster:
#         labels[sample_id] = cluster_id
#     return labels

In [334]:
# kmean = KMeans(k=2, n_iter=150, plot_step=False)

In [335]:
# # from sklearn.datasets import make_blobs
# # X, y = make_blobs(centers=3, n_samples=500, n_features=2, shuffle=True, random_state=40)
# y_predict = kmean.predict(X)

In [336]:

# accuracy = np.sum(y == y_predict) / len(y)

In [337]:

# accuracy

In [338]:

# s=y_predict.tolist()
# # s

In [339]:
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt

# from sklearn.cluster import KMeans
# from sklearn.preprocessing import StandardScaler, normalize
# from sklearn.decomposition import PCA
# from sklearn.metrics import silhouette_score


In [340]:
# sse = {}
# for k in range(1, 10):
#     kmeans = KMeans(n_clusters=k, max_iter=1000).fit(X)
#     sse[k] = kmeans.inertia_ # Inertia: Sum of distances of samples to their closest cluster center
# plt.figure()
# plt.plot(list(sse.keys()), list(sse.values()))
# plt.xlabel("Number of cluster")
# plt.ylabel("SSE")
# plt.show()

In [341]:
# import numpy as np
# import matplotlib.pyplot as plt
# # from sklearn.datasets import make_blobs

In [342]:
# class KMeans:
    
#     def __init__(self, k=5, n_iter=100, plot_step=False):
        
#         self.k = k
#         self.n_iter = n_iter
#         self.plot_step = plot_step
#         self.clusters = [[] for _ in range(self.k)]    # list of each cluster
#         self.centroids = []     # center of each cluster
        
#     def distance(self, x1, x2):
#         return np.sqrt(np.sum((x1-x2)**2))
    
#     def cluster_plot(self):
        
#         fig, ax = plt.subplots(figsize=(12, 8))
        
#         for i, index in enumerate(self.clusters):
#             point = self.X[index].T
#             ax.scatter(*point)
        
#         for centroid in self.centroids:
#             ax.scatter(*centroid, marker='x', color='black', linewidth=2)
#         plt.show()
        
#     def predict(self, X):
        
#         self.X = X
#         self.n_samples, self.n_features = X.shape
        
#         # initialize k random centroids
#         k_random_sample_ids = np.random.choice(self.n_samples, self.k, replace=False)
#         self.centroids = [self.X[ids] for ids in k_random_sample_ids]
        
#         # optimize clusters
#         for _ in range(self.n_iter):
            
#             # update clusters
#             self.clusters = self._create_clusters(self.centroids)     # get clusters from create clusters
#             if self.plot_step:
#                 self.cluster_plot()
                
#             # update centroids
#             old_centroids = self.centroids
#             self.centroids = self._get_new_centroids(self.clusters)
            
#             # check clusters converged
#             if self._is_converged(old_centroids, self.centroids):
#                 break
                
#         return self._get_cluster_label(self.clusters)
    
            
#     def _create_clusters(self, centroids):
        
#         clusters = [[] for _ in range(self.k)]
        
#         for ids, sample in enumerate(self.X):
#             centroid_id = self._closest_centroid(sample, centroids)
#             clusters[centroid_id].append(ids)
#         return clusters
            
            
#     def _closest_centroid(self, sample, centroids):
        
#         distances = [self.distance(sample, centroid) for centroid in centroids]
#         closest_id = np.argmin(distances)
#         return closest_id
        
#     def _get_new_centroids(self, clusters):
        
#         centroids = np.zeros((self.k, self.n_features))
#         for cluster_id, cluster in enumerate(clusters):
#             new_centroid = np.mean(X[cluster], axis=0)
#             centroids[cluster_id] = new_centroid
#         return centroids
    
#     def _is_converged(self, old_centroids, new_centroids):
        
#         distances = [self.distance(old_centroids[i], new_centroids[i]) for i in range(self.k)]
#         return sum(distances) == 0
    
#     def _get_cluster_label(self, clusters):
        
#         labels = np.empty(self.n_samples)
#         for cluster_id, cluster in enumerate(clusters):
#             for sample_id in cluster:
#                 labels[sample_id] = cluster_id
#         return labels

In [343]:
# kmean = KMeans(k=2, n_iter=150, plot_step=False)

In [344]:
# y_predict = kmean.predict(X)
# print(kmean)

In [345]:
# l=kmean.labels
# l

In [346]:
# from sklearn.metrics import confusion_matrix,classification_report
# print(confusion_matrix(s,y))
# print(classification_report(s,y))

In [347]:
# # knn = KNeighborsClassifier(n_neighbors = 15, metric='manhattan')# metric='euclidean') #metric='minkowski') 
# # knn.fit(X_train, y_train) 
# from sklearn import metrics 
# from sklearn.metrics import precision_recall_fscore_support
# # kmeans.score(X_test, y_test) 
# # y_pred=knn.predict(X_test)
# acc=(metrics.accuracy_score(s,y)*100)
# print(acc)    
# # knn.score(X_test, y_test) 

# from sklearn.metrics import precision_score
# pre=(precision_score(s,y)*100) #average='binary')*100)
# print(pre)

# from sklearn.metrics import recall_score
# rec=(recall_score(s,y)*100)# average='binary')*100)
# print(rec)

# from sklearn.metrics import f1_score
# f1=(f1_score(s,y))# average='binary')*100)
# print(f1) 

## **Secure K-means with Manhattan Distance**

In [474]:
# Library Declaration  
import numpy as np
import pandas as pd 
# Data Input
df = pd.read_table('breast-cancer-wisconsin.data', sep=',', names=["Sample code number", "Clump Thickness", "Uniformity of Cell Size", "Uniformity of Cell Shape", "Marginal Adhesion", "Single Epithelial Cell Size","Bare Nuclei", "Bland Chromatin", "Normal Nucleoli","Mitoses","Class"]) 
# print(df.head)
# Data Cleaning
df["Bare Nuclei"][df["Bare Nuclei"]=='?']='0'
df["Bare Nuclei"] = df["Bare Nuclei"].astype(str).astype(int)
# df.info()
# pd.to_numeric(df["Bare Nuclei"])
# Data Cleaning

df=df.drop(["Sample code number"], axis = 1)
# print(df.shape)
# Data Cleaning

def Class_value(Class): 
     if Class == 2: 
         return 1
     else: 
         return 0
  
df['Class'] = df['Class'].apply(Class_value) 
#df['Class'].head(10)
sf=df
y = sf["Class"].astype(float).values.tolist()
# y

df=df.drop(["Class"], axis = 1)

dataset = df.astype(float).values.tolist()

X = df.values #returns a numpy array
X

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


array([[ 5,  1,  1, ...,  3,  1,  1],
       [ 5,  4,  4, ...,  3,  2,  1],
       [ 3,  1,  1, ...,  3,  1,  1],
       ...,
       [ 5, 10, 10, ...,  8, 10,  2],
       [ 4,  8,  6, ..., 10,  6,  1],
       [ 4,  8,  8, ..., 10,  4,  1]])

In [475]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA
from sklearn.metrics import silhouette_score

In [486]:
class KMeans:
    
    def __init__(self, k=5, n_iter=100, plot_step=False):
        
        self.k = k
        self.n_iter = n_iter
        self.plot_step = plot_step
        self.clusters = [[] for _ in range(self.k)]    # list of each cluster
        self.centroids = []     # center of each cluster
        
    def distance(self, x1, x2):
      disce = 0.0
      for i in range(len(x1)-1):
        if (x1[i]>=x2[i]):
          disce +=(x1[i] - x2[i])
        else:
          disce += (x2[i] - x1[i])
      return disce
      #print(distance)


    # def distance(self, x1, x2):
    #     return np.sqrt(np.sum((x1-x2)**2))
    
    def cluster_plot(self):
        
        fig, ax = plt.subplots(figsize=(12, 8))
        
        for i, index in enumerate(self.clusters):
            point = self.X[index].T
            ax.scatter(*point)
        
        for centroid in self.centroids:
            ax.scatter(*centroid, marker='x', color='black', linewidth=2)
        plt.show()
        
    def predict(self, X):
        
        self.X = X
        self.n_samples, self.n_features = X.shape
        
        # initialize k random centroids
        k_random_sample_ids = np.random.choice(self.n_samples, self.k, replace=False)
        self.centroids = [self.X[ids] for ids in k_random_sample_ids]
        
        # optimize clusters
        for _ in range(self.n_iter):
            
            # update clusters
            self.clusters = self._create_clusters(self.centroids)     # get clusters from create clusters
            if self.plot_step:
                self.cluster_plot()
                
            # update centroids
            old_centroids = self.centroids
            self.centroids = self._get_new_centroids(self.clusters)
            
            # check clusters converged
            if self._is_converged(old_centroids, self.centroids):
                break
                
        return self._get_cluster_label(self.clusters)
    
            
    def _create_clusters(self, centroids):
        
        clusters = [[] for _ in range(self.k)]
        
        for ids, sample in enumerate(self.X):
            centroid_id = self._closest_centroid(sample, centroids)
            clusters[centroid_id].append(ids)
        return clusters
            
            
    def _closest_centroid(self, sample, centroids):
        
        distances = [self.distance(sample, centroid) for centroid in centroids]
        closest_id = np.argmin(distances)
        return closest_id
        
    def _get_new_centroids(self, clusters):
        # print(clusters)
        centroids = np.zeros((self.k, self.n_features))
        for cluster_id, cluster in enumerate(clusters):
          # print("dfd:",X[cluster])
          new_centroid = np.mean(X[cluster], axis=0)
          centroids[cluster_id] = new_centroid
          # print("fff:",centroids)
        return centroids
    
    def _is_converged(self, old_centroids, new_centroids):
        distances = [self.distance(old_centroids[i], new_centroids[i]) for i in range(self.k)]
        return sum(distances) == 0
    
    def _get_cluster_label(self, clusters):
        
        labels = np.empty(self.n_samples)
        for cluster_id, cluster in enumerate(clusters):
            for sample_id in cluster:
                labels[sample_id] = cluster_id
        return labels

In [487]:
kmean = KMeans(k=2, n_iter=150, plot_step=False)
y_predict = kmean.predict(X)

dfd: [[ 5  4  4 ...  3  2  1]
 [ 6  8  8 ...  3  7  1]
 [ 8 10 10 ...  9  7  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]
dfd: [[5 1 1 ... 3 1 1]
 [3 1 1 ... 3 1 1]
 [4 1 1 ... 3 1 1]
 ...
 [3 1 1 ... 2 1 2]
 [3 1 1 ... 1 1 1]
 [2 1 1 ... 1 1 1]]
dfd: [[ 5  4  4 ...  3  2  1]
 [ 6  8  8 ...  3  7  1]
 [ 8 10 10 ...  9  7  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]
dfd: [[5 1 1 ... 3 1 1]
 [3 1 1 ... 3 1 1]
 [4 1 1 ... 3 1 1]
 ...
 [3 1 1 ... 2 1 2]
 [3 1 1 ... 1 1 1]
 [2 1 1 ... 1 1 1]]
dfd: [[ 5  4  4 ...  3  2  1]
 [ 6  8  8 ...  3  7  1]
 [ 8 10 10 ...  9  7  1]
 ...
 [ 5 10 10 ...  8 10  2]
 [ 4  8  6 ... 10  6  1]
 [ 4  8  8 ... 10  4  1]]
dfd: [[5 1 1 ... 3 1 1]
 [3 1 1 ... 3 1 1]
 [4 1 1 ... 3 1 1]
 ...
 [3 1 1 ... 2 1 2]
 [3 1 1 ... 1 1 1]
 [2 1 1 ... 1 1 1]]


In [479]:
# from sklearn.datasets import make_blobs
# X, y = make_blobs(centers=3, n_samples=500, n_features=2, shuffle=True, random_state=40)

# accuracy = np.sum(y == y_predict) / len(y)
# accuracy
s=y_predict.tolist()
# s

In [480]:
from sklearn.metrics import confusion_matrix,classification_report
print(confusion_matrix(s,y))
print(classification_report(s,y))

[[211  11]
 [ 30 447]]
              precision    recall  f1-score   support

         0.0       0.88      0.95      0.91       222
         1.0       0.98      0.94      0.96       477

    accuracy                           0.94       699
   macro avg       0.93      0.94      0.93       699
weighted avg       0.94      0.94      0.94       699



In [481]:
# knn = KNeighborsClassifier(n_neighbors = 15, metric='manhattan')# metric='euclidean') #metric='minkowski') 
# knn.fit(X_train, y_train) 
from sklearn import metrics 
from sklearn.metrics import precision_recall_fscore_support
# kmeans.score(X_test, y_test) 
# y_pred=knn.predict(X_test)
acc=(metrics.accuracy_score(s,y)*100)
print(acc)    
# knn.score(X_test, y_test) 

from sklearn.metrics import precision_score
pre=(precision_score(s,y)*100) #average='binary')*100)
print(pre)

from sklearn.metrics import recall_score
rec=(recall_score(s,y)*100)# average='binary')*100)
print(rec)

from sklearn.metrics import f1_score
f1=(f1_score(s,y))# average='binary')*100)
print(f1) 

94.13447782546494
97.59825327510917
93.71069182389937
0.9561497326203208


## **Final Version of SecureKmeans**

In [415]:
# # Library Declaration  
# import numpy as np
# import pandas as pd 
# # Data Input
# df = pd.read_table('breast-cancer-wisconsin.data', sep=',', names=["Sample code number", "Clump Thickness", "Uniformity of Cell Size", "Uniformity of Cell Shape", "Marginal Adhesion", "Single Epithelial Cell Size","Bare Nuclei", "Bland Chromatin", "Normal Nucleoli","Mitoses","Class"]) 
# # print(df.head)
# # Data Cleaning
# df["Bare Nuclei"][df["Bare Nuclei"]=='?']='0'
# df["Bare Nuclei"] = df["Bare Nuclei"].astype(str).astype(int)
# # df.info()
# # pd.to_numeric(df["Bare Nuclei"])
# # Data Cleaning

# df=df.drop(["Sample code number"], axis = 1)
# # print(df.shape)
# # Data Cleaning

# def Class_value(Class): 
#      if Class == 2: 
#          return 1
#      else: 
#          return 0
  
# df['Class'] = df['Class'].apply(Class_value) 
# #df['Class'].head(10)
# sf=df
# y = sf["Class"].astype(float).values.tolist()
# # y

# df=df.drop(["Class"], axis = 1)

# dataset = df.astype(float).values.tolist()

# X = df.values #returns a numpy array
# X

In [414]:
# sse={}
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt

# from sklearn.cluster import KMeans
# from sklearn.preprocessing import StandardScaler, normalize
# from sklearn.decomposition import PCA
# from sklearn.metrics import silhouette_score

# for k in range(1, 10):
#     kmeans = KMeans(n_clusters=k, max_iter=1000).fit(X)
#     sse[k] = kmeans.inertia_ # Inertia: Sum of distances of samples to their closest cluster center
# plt.figure()
# plt.plot(list(sse.keys()), list(sse.values()))
# plt.xlabel("Number of cluster")
# plt.ylabel("SSE")
# plt.show()

In [406]:
# import numpy as np
# class Kmeans:
  
#   def __init__(self, n_clusters=4):
#     self.K = n_clusters
  
#   def fit(self, X):
#     self.centroids = X[np.random.choice(len(X), self.K, replace=False)]
#     self.intial_centroids = self.centroids
#     self.prev_label,  self.labels = None, np.zeros(len(X))
#     while not np.all(self.labels == self.prev_label) :
#       self.prev_label = self.labels
#       self.labels = self.predict(X)
#       self.update_centroid(X)
#     return self
  
#   def predict(self, X):
#     return np.apply_along_axis(self.compute_label, 1, X)
    
#   # def distance(self, x1, x2):
#   #   disce = 0.0
#   #   for i in range(len(x1)-1):
#   #     if (x1[i]>=x2[i]):
#   #       disce +=(x1[i] - x2[i])
#   #     else:
#   #       disce += (x2[i] - x1[i])
#   #   return disce

#   # def compute_label(self, x):
#   #   # print(np.sqrt(np.sum((self.centroids - x)**2, axis=1)))
#   #   disce = 0.0
#   #   for i in range(2):
#   #     for j in range(len(x)-1):
#   #       if (self.centroids[i][j]>=x[j]):
#   #         disce +=(self.centroids[i][j] - x[i])
#   #       else:
#   #         disce += (x[i] -self.centroids[i][j])
#   #   print(disce)
#   #   # return np.argmin(disce)

#   def compute_label(self, x):
#     print(np.sqrt(np.sum((self.centroids - x)**2, axis=1)))
#     return np.argmin(np.sqrt(np.sum((self.centroids - x)**2, axis=1)))
  
#   def update_centroid(self, X):
#     self.centroids = np.array([np.mean(X[self.labels == k], axis=0)  for k in range(self.K)])

In [408]:
# kmeans = Kmeans(n_clusters=2).fit(X)

In [409]:
# s=kmeans.labels

In [413]:
# s

In [411]:
# from sklearn.metrics import confusion_matrix,classification_report
# print(confusion_matrix(s,y))
# print(classification_report(s,y))

In [412]:
# # knn = KNeighborsClassifier(n_neighbors = 15, metric='manhattan')# metric='euclidean') #metric='minkowski') 
# # knn.fit(X_train, y_train) 
# from sklearn import metrics 
# from sklearn.metrics import precision_recall_fscore_support
# # kmeans.score(X_test, y_test) 
# # y_pred=knn.predict(X_test)
# acc=(metrics.accuracy_score(s,y)*100)
# print(acc)    
# # knn.score(X_test, y_test) 

# from sklearn.metrics import precision_score
# pre=(precision_score(s,y)*100) #average='binary')*100)
# print(pre)

# from sklearn.metrics import recall_score
# rec=(recall_score(s,y)*100)# average='binary')*100)
# print(rec)

# from sklearn.metrics import f1_score
# f1=(f1_score(s,y))# average='binary')*100)
# print(f1) 